### ISSUE TITLE
Getting Unable to find type [PassphraseObject].

### ISSUE THREAD

**Issue by simonsabin** [lagebj/Passphraser#1]
I'm getting this error at times on my machine and on a devops hosted agent 
`Unable to find type [PassphraseObject].`

Any ideas

**Comment by lagebj** [comment]
Hi @simonsabin 
Can you try running this command on the computer(s)?
```
C:\> Get-Module Passphrase*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.0                   PassphraseObject.Class
Script     2.0.1                 Passphraser                         New-Passphrase
```

The `PassphraseObject` class is defined in file `.\classes\PassphraseObject.Class.ps1` and loaded in the module manifest file `Passphraser.psd1`. Check that both these files are available at the module root folder. :)

**Comment by simonsabin** [comment]
Both modules are loaded. What do you mean by root folder?

Simon Sabin

________________________________

**Comment by lagebj** [comment]
To find the module root folder you can use
```
C:\> (Get-Module Passphraser).ModuleBase
```
But since both modules are loaded the files are correct.

Is this a problem all the time or ocassionally?
Which version of the module are you using?
Are you loading the module in your profile or manually?

**Comment by lagebj** [comment]
@simonsabin I haven't heard anymore from you and will close this issue. Please feel free to reopen if this is still a problem for you :)
