### ISSUE TITLE
Option for non-offensive / negative words

### ISSUE THREAD

**Issue by dominikduennebacke** [lagebj/Passphraser#2]
Thanks for providing this great module. Today I checked it out and came across this passphrase combination: "arrogant.embarrassed.hapless.kill."

I cannot send this password to a user in a corporate environment. As I would do this within an automated process there is no human oversight. So ideally the word list could be stripped of offensive or negative perceived words. Otherwise perhaps a switch could be included to not use offensive / negative words.

**Comment by lagebj** [comment]
Hi @dominikduennebacke, thank you for checking out my module :) I can understand why you would not want to use that password in a corporate environment. I will take a look at this as soon as possible.

**Comment by lagebj** [comment]
@dominikduennebacke v2.1.0 is released to the Powershell Gallery. The new version contains a curated list of words that should not contain negative and offensive words. Please let me know if you still have concerns about the list. 😃
